Repository wecode-bootcamp-korea/18-2nd-Heuream-frontend, pull requests merged in 2021-04, with the labels that each got.

#3 [18기 양지은] Add: Login과 Join 레이아웃 초기 세팅 완료
  package-lock.json
  package.json
  public/index.html
  src/Pages/Login/Join.js
  src/Pages/Login/Login.js
  src/Pages/Login/Modal.js
  src/Routes.js
  src/config.js
Labels: Status: Accepted, Status: 수정 요청

#5 [18기 양지은] Add: Nav bar 초기 레이아웃 완료.
  public/data/SearchList.json
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Components/Nav/SearchDataList.js
  src/Components/Nav/SearchModal.js
  src/Pages/Login/Join.js
  src/Pages/Login/Login.js
  src/Routes.js
Labels: Status: Accepted

#6 [18기 정재욱] Add: 리뷰 반영 수정 완료, 모달창 구현, infoFooter구현, rebase 완료
  package-lock.json
  package.json
  public/data/data.js
  public/data/productDetail.json
  src/Components/Loading/Loading.js
  src/Pages/Login/Modal.js
  src/Pages/MyPage/MyPage.js
  src/Pages/Product/Component/DetailBtn/DetailBtn.js
  src/Pages/Product/Component/DetailImage/DetailImage.js
  src/Pages/Product/Component/DetailInfo/Components/InfoFooter/InfoFooter.js
  src/Pages/Product/Component/DetailInfo/Components/InfoHeader/InfoHeader.js
  src/Pages/Product/Component/DetailInfo/Components/InfoMain/Components/Graph/Graph.js
  src/Pages/Product/Component/DetailInfo/Components/InfoMain/Components/Table/Components/TableContent/TableContent.js
  src/Pages/Product/Component/DetailInfo/Components/InfoMain/Components/Table/Table.js
  src/Pages/Product/Component/DetailInfo/Components/InfoMain/InfoMain.js
  src/Pages/Product/Component/DetailInfo/Components/SizeButton/SizeButton.js
  src/Pages/Product/Component/DetailInfo/DetailInfo.js
  src/Pages/Product/Component/DetailModal/Components/EachSize/EachSize.js
  src/Pages/Product/Component/DetailModal/DetailModal.js
  src/Pages/Product/Component/TabMenu/TabMenu.js
  src/Pages/Product/Product.js
  src/Styles/theme.js
Labels: Status: 리뷰 요청

#4 [18기 배담호] Add: 리뷰반영 및 메인 페이지네이션 기능 구현완료, 정렬기능 구현완료
  log
  package-lock.json
  package.json
  public/data/commentData.json
  src/Pages/Shop/Components/ButtonPage.js
  src/Pages/Shop/Components/Modal.js
  src/Pages/Shop/Components/ModalChild.js
  src/Pages/Shop/Components/Product.js
  src/Pages/Shop/Components/ProductList.js
  src/Pages/Shop/Shop.js
  src/Routes.js
  src/Styles/GlobalStyles.js
  src/Styles/media.js
Labels: Status: 리뷰 요청
